name: Build Docker Image (GraalVM)
on:
  push:
    branches:
      - main
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: quay.io/sewerynmi
      DOCKER_REPO: quarkus-microservices-vintagestore-books
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Project
        run: |
            mvn package -Dquarkus.package.type=jar

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_ROBOT_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_ROBOT_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:1.0.0
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:${{ github.sha }}

      - name: Build and push with tags
        run: |
          if [ "$GITHUB_REF_NAME" = "main" ]
          then
            TAG=latest
          elif [[ $GITHUB_REF_NAME =~ (eahw-[0-9]*) ]]
          then
            TAG=${match/#E/E}${BASH_REMATCH/#E/E}
          else
            TAG=${GITHUB_SHA}
          fi
          docker manifest create ${DOCKER_REGISTRY}/${DOCKER_REPO}:${TAG} --amend ${DOCKER_REGISTRY}/${DOCKER_REPO}:${GITHUB_SHA}-amd --amend ${DOCKER_REGISTRY}/${DOCKER_REPO}:${GITHUB_SHA}-arm
          docker manifest push ${DOCKER_REGISTRY}/${DOCKER_REPO}:${TAG}